import { Lato, Roboto } from "next/font/google";
import "./globals.css";
import Footer from "@/src/compronent/Home/Footer";
import Header from "@/src/compronent/header/header";

const lato = Lato({
  subsets: ["latin"],
  variable: "--font-lato",
  weight: ["400", "700"], 
  display: "swap",
});

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  weight: ["400", "700"],
  display: "swap",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${lato.variable} ${roboto.variable} antialiased`}
      >
      
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
